import turtle
rayan = turtle.clone()
rayan.shape('circle')
rayan.color('white')
turtle.color('white')
turtle.bgcolor('purple')
turtle.pencolor('white')
turtle.pensize(5)
turtle.left(90)
turtle.forward(150)
turtle.color('yellow')
turtle.right(90)
turtle.forward(75)
turtle.right(90)
turtle.forward(150)
turtle.color('green')
turtle.pensize(10)
turtle.forward(150)
turtle.left(90)
turtle.forward(75)
turtle.color('blue')
turtle.shape('triangle')
turtle.left(90)
turtle.forward(150)


turtle.mainloop()
